name: Run Monthly Scraper

on:
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Scraper
        run: python scrape.py

      - name: Commit and Push CSV result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Cek apakah file ada
          if [ -f berita-mei-2026.csv ]; then
            git add berita-mei-2026.csv
            
            # Commit hanya jika ada perubahan. 
            # Jika tidak ada perubahan, perintah ini tidak akan membuat Actions jadi merah.
            git commit -m "Update hasil scraping $(date)" || echo "Tidak ada perubahan pada data."
            
            # Push perubahan ke repositori
            git push origin main || echo "Tidak ada yang perlu di-push."
          else
            echo "File berita-mei-2026.csv tidak ditemukan. Melewati proses upload."
          fi
