name: Run Monthly Scraper

on:
  schedule:
    # Berjalan otomatis setiap tanggal 1 jam 00:00 UTC
    - cron: '0 0 1 * *' 
  workflow_dispatch: # Memungkinkan kamu menjalankan manual dari tombol di GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: python scrape.py

      - name: Commit and Push CSV result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add berita-mei-2026.csv
          git commit -m "Update hasil scraping $(date)"
          git push
